### ISSUE TITLE
issues with real-debrid and kodi plugins using resolveurl

### ISSUE THREAD

**Issue by 0xTT** [Gujal00/ResolveURL#142]
Many people are experiencing issues, where the latest update has stopped working with addons in kodi such as The Crew. 

https://www.reddit.com/r/Addons4Kodi/comments/viw0hh/resolveurl_error_rd_links_wont_load/

Please let me know which debug logs you would need to troubleshoot. I would assume this is reproducible on your own build. Thank you.

**Comment by Gujal00** [comment]
It has nothing to do with any latest resolveurl update.
No idea why, but can see that RD have banned ResolveURL's User Agent which looks like `ResolveURL for Kodi/5.1.70`
Using a browser User Agent works fine. Can you test with commit https://github.com/Gujal00/ResolveURL/commit/77c2744f751d396e1adb9cf1c25624947f0821b8 and report back?

**Comment by 123Venom** [comment]
RD strikes again.  When will people learn that thing needs to get shit canned.  They openly replied to a user about their new DMCA compliance with `infringing_file` and `magnet_error` new api responses but users still pucker up....lol.  I've confirmed them to be real and let RD expire and won't use that crap ever again!!  Have fun with rubbish!!

**Comment by 123Venom** [comment]
<img width="368" alt="RD_infringing file3" src="https://user-images.githubusercontent.com/46383815/175757663-bdd6c9a7-b597-44fd-b635-7b7d1377132e.PNG">

<img width="571" alt="RD_2" src="https://user-images.githubusercontent.com/46383815/175757672-53f119ed-d3d3-44dd-9328-110e3d28d2e3.PNG">

Not worth using anymore!!

**Comment by 123Venom** [comment]
<img width="825" alt="RD_infringing file" src="https://user-images.githubusercontent.com/46383815/175758573-96dbc7e5-3334-40ca-8b54-77de84f753d1.PNG">

For a month straight I could no longer cache anything to my RD account and I'd receive this new `INFRINGING_FILE` server response.  Maybe it was targeted to my area idk but I could not get around it and made RD useless to me so I let my account expire.  I for one would NEVER use RD again!  Before I let it expire I did notice the cached content on RD was slowly dwindling down and AD had nearly the same source content.  All I could imagine is as RD cached torrents expire they are going to be removed and the service will slowly turn to absolute dog shit...have fun with it.  I think RD is done.

**Comment by Gujal00** [comment]
Looks like they have allowed ResolveURL agent back. I think this was done by mistake by RD. Most probably they enabled cloudflare browser fingerprinting on the api.real-debrid.com site which will then start comparing user-agents to known ssl finger prints and then reject if not matching.
I am now able to authorise and get the regex list for supported hosters (which is stored in the function cache)
So the last release 5.1.70 should work now

**Comment by bleak-lodge** [comment]
@Gujal00 that doesn't seem to be the problem - still fails resolving with the smr ua removed.
I switched to `requests` instead of the `net` wrapper and it seems to be working. I noticed script.module.urllib3 and script.module.requests recently updated, not sure if that has any relation, ie they adjusted to something that needs to.
Not saying this as a solution, just food for thought of what might be wrong - haven't vented the `net` script that much to debug it.
Here's my modded realdebrid.py script with usage of requests - ofc you need to import script.module.requests on addon.xml for it to work:
https://gist.github.com/bleak-lodge/c56986ddb6f0efbf7f5a310b5a2fceb4

**Comment by 0xTT** [comment]
Started working again for me. Reinstalled repo version and reset cache and defaults in ResolveURL. Then re-authorized RD successfully and all seems okay.

**Comment by cgcgcgcgcg** [comment]
What worked for me earlier -and still works-, was:
If ResolveURL issues persist, open File Manager > .home > userdata > addon_data, delete script.module.resolveurl , restart your build and authorize ResolveURL.

**Comment by cgcgcgcgcg** [comment]
> Looks like they have allowed ResolveURL agent back. I think this was done by mistake by RD. Most probably they enabled cloudflare browser fingerprinting on the api.real-debrid.com site which will then start comparing user-agents to known ssl finger prints and then reject if not matching. I am now able to authorise and get the regex list for supported hosters (which is stored in the function cache) with ResolveURL useragent, 12 hours ago this was not working and thats why i did a commit use browser ua instead. So the last release 5.1.70 should work now without any changes

Some peeps still have issues and I'm suspecting not all RD servers worldwide have been updated with the "fix" yet.

**Comment by Gujal00** [comment]
> @Gujal00 that doesn't seem to be the problem - still fails resolving with the smr ua removed. I switched to `requests` instead of the `net` wrapper and it seems to be working. I noticed script.module.urllib3 and script.module.requests recently updated, not sure if that has any relation, ie they adjusted to something that needs to. Not saying this as a solution, just food for thought of what might be wrong - haven't vented the `net` script that much to debug it. Here's my modded realdebrid.py script with usage of requests - ofc you need to import script.module.requests on addon.xml for it to work: https://gist.github.com/bleak-lodge/08158900fb9edbb009ed23eb2bafbc55

Exactly my point, RD seems to have enabled cloudflare browser ssl fingerprinting on the api.real-debrid.com unnecessarily. No browser is going to talk that website and in all cases it will be applications talking to it. urllib3 has better ssl implementation than the default python2/3 urllib2/urllib.request and may work better with cloudflare. I try to keep away from requests and urrlib3 because of resolveurl still running on old versions of Kodi such as SPMC. If I start adding dependency on urllib3 then the resolveurl may only work on Kodi version 18 and above.
It is not just ResolveURL that is affected, there have been reports of intermittent RD issues on APKs as well which is completely outside of Kodi/python.

**Comment by bugatsinho** [comment]
Hey mate!!  i know you want to keep it clean from new imports but maybe is a good idea to use six.PY in this case?

**Comment by Gujal00** [comment]
> Hey mate!! i know you want to keep it clean from new imports but maybe is a good idea to use six.PY in this case?

Yes, it uses six and that is how it works on Kodi 16,17,18, 19 and 20. requests and urllib3 are an external dependency and six wont help in this case

**Comment by bleak-lodge** [comment]
@Gujal00 just checked smpc 16, and it works just fine with requests, as does my add-on - fyi.

**Comment by bleak-lodge** [comment]
It seems the reversion of rd's changes that broke smr is temporal, so it'll break again sooner or later.
https://twitter.com/RealDebrid/status/1541716244721766402

**Comment by Gujal00** [comment]
@bleak-lodge Have added ALPN support in [this commit](https://github.com/Gujal00/ResolveURL/commit/a100064c7d801d0b9a09e72a603bc37981d3ebc7)

I can now see that it is sending all the ciphers in the Client-Hello as below. Please test if it is working correctly for you.
```
CONNECT api.real-debrid.com:443 HTTP/1.0
Host: api.real-debrid.com:443

Version: 3.3 (TLS/1.2)
Random: 43 4D D4 91 D3 DA 74 AF EB 90 DE 98 BB 0C 17 CE 0C 4F 53 5F BD 69 37 00 94 E9 76 06 68 A0 BD 76
"Time": 13/07/2047 5:48:51 PM
SessionID: 16 E0 BB 8F 29 69 F9 0B 7F 63 97 D0 2B 87 82 FF 45 04 48 EE B9 AA 06 40 A8 38 66 9E 9E 9D 28 F0
Extensions: 
	server_name	api.real-debrid.com
	ec_point_formats	uncompressed [0x0], ansiX962_compressed_prime [0x1], ansiX962_compressed_char2 [0x2]
	supported_groups	x25519 [0x1d], secp256r1 [0x17], x448 [0x1e], secp521r1 [0x19], secp384r1 [0x18]
	SessionTicket	empty
	ALPN		http/1.1
	encrypt_then_mac (RFC7366)	empty
	extended_master_secret	empty
	signature_algs	ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, ed25519, ed448, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha224, ecdsa_sha1, rsa_sha224, rsa_pkcs1_sha1, dsa_sha224, dsa_sha1, dsa_sha256, dsa_sha384, dsa_sha512
	supported_versions	Tls1.3, Tls1.2, Tls1.1
	psk_key_exchange_modes	01 01
	key_share	00 24 00 1D 00 20 A9 1C 0C 9D 2B DA 7B 9D 97 E8 A3 AB EF D6 10 CF 0F E8 FA B2 54 F1 70 AA 4F 52 C2 92 31 3A 06 61
	padding		177 null bytes
Ciphers: 
	[1302]	TLS_AES_256_GCM_SHA384
	[1303]	TLS_CHACHA20_POLY1305_SHA256
	[1301]	TLS_AES_128_GCM_SHA256
	[C02C]	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
	[C030]	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	[009F]	TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
	[CCA9]	TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
	[CCA8]	TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
	[CCAA]	TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256
	[C02B]	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
	[C02F]	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	[009E]	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
	[C024]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
	[C028]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
	[006B]	TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
	[C023]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
	[C027]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
	[0067]	TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
	[C00A]	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
	[C014]	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
	[0039]	TLS_DHE_RSA_WITH_AES_256_CBC_SHA
	[C009]	TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
	[C013]	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
	[0033]	TLS_DHE_RSA_WITH_AES_128_CBC_SHA
	[009D]	TLS_RSA_WITH_AES_256_GCM_SHA384
	[009C]	TLS_RSA_WITH_AES_128_GCM_SHA256
	[003D]	TLS_RSA_WITH_AES_256_CBC_SHA256
	[003C]	TLS_RSA_WITH_AES_128_CBC_SHA256
	[0035]	TLS_RSA_WITH_AES_256_CBC_SHA
	[002F]	TLS_RSA_WITH_AES_128_CBC_SHA
	[00FF]	TLS_EMPTY_RENEGOTIATION_INFO_SCSV

Compression: 
	[00]	NO_COMPRESSION
```

**Comment by Gujal00** [comment]
ResolveURL 5.1.71 released with changes as suggested by RD tech.
Please test and get back if working or not

**Comment by bleak-lodge** [comment]
Yes it works (tested spmc 16 & kodi 19, auth & resolve), lets see how it flies when rd redo their changes.

**Comment by Wanderer189** [comment]
I know this is old, has the issue returned??
